name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: reeltone-env  # link this job to your environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            cd ~/reeltone
            git fetch --all
            git reset --hard origin/main
            cd server
            sudo docker build -t reeltone-server .
            sudo docker rm -f reeltone-server || true
            sudo docker run -d \
              -p 127.0.0.1:8888:8888 \
              --env-file /home/${{ secrets.AZURE_VM_USER }}/.env \
              --name reeltone-server \
              reeltone-server
