name: Deploy frontend to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: reeltone-env

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.AZURE_SERVER_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            # Ensure Docker & Compose are installed
            sudo apt-get update -y
            sudo apt-get install -y docker.io docker-compose-plugin
            sudo systemctl enable docker
            sudo systemctl start docker

            # Verify installation
            docker --version
            docker compose version

            # Pull latest code
            rm -rf ~/reeltone
            git clone https://github.com/NK8998/reeltone.git ~/reeltone

            # Go into client dir
            cd ~/reeltone/client

            # Run docker compose
            sudo docker compose up -d --build

            # Clean up unused resources
            sudo docker system prune -af
